version: "3.8"

services:
  redis:
    image: redis
  api:
    build: api
    ports:
      - "5001:5000"
    depends_on:
      - redis
  web:
    image: bitelxux/scadabr
    ports:
      - "8081:8080"
      - "3307:3306"
    privileged: true
    volumes:
      # - ./db:/var/lib/mysql
      - data:/var/lib/mysql
volumes:
  data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./db